# Generated by Django 4.2.24 on 2025-09-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("zona", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(max_length=200)),
                (
                    "tag",
                    models.CharField(
                        help_text="Código o identificación única",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(
                        choices=[
                            ("MECANICO", "Mecánico"),
                            ("ELECTRICO", "Eléctrico"),
                            ("INSTRUMENTACION", "Instrumentación"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "criticidad",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MEDIA", "Media"),
                            ("BAJA", "Baja"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
