# Generated by Django 4.2.24 on 2025-09-29 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("equipos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PREVENTIVO", "Preventivo"),
                            ("PREDICTIVO", "Predictivo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("SEMANAL", "Semanal"),
                            ("MENSUAL", "Mensual"),
                            ("TRIMESTRAL", "Trimestral"),
                            ("ANUAL", "Anual"),
                            ("HORAS", "Por horas"),
                            ("CONDICION", "Por condición"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condicion_umbral",
                    models.CharField(
                        blank=True,
                        help_text="Sólo si es por condición: ej. vibración > x mm/s",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("recursos_previstos", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_mantenimiento",
                        to="equipos.equipo",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planes_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
