# Generated by Django 4.2.24 on 2025-09-29 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ordenes", "0002_planmantenimiento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "especialidad",
                    models.CharField(
                        choices=[
                            ("MECANICO", "Mecánico"),
                            ("ELECTRICO", "Eléctrico"),
                            ("INSTRUMENTACION", "Instrumentación"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ubicacion", models.CharField(max_length=100)),
                ("stock", models.IntegerField(default=0)),
                ("unidad", models.CharField(default="unid", max_length=20)),
                ("proveedor", models.CharField(blank=True, max_length=100, null=True)),
                ("stock_minimo", models.IntegerField(default=0)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsoRepuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos_repuesto",
                        to="ordenes.ordentrabajo",
                    ),
                ),
                (
                    "repuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordenes.repuesto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "repuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="ordenes.repuesto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
