# Generated by Django 4.2.24 on 2025-09-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ordenes", "0003_repuesto_usorepuesto_movinventario"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialOT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resumen", models.TextField(blank=True, null=True)),
                (
                    "costo_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "mtbf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tiempo medio entre fallas (horas)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "mttr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tiempo medio de reparación (horas)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "orden",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="ordenes.ordentrabajo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="evidencias/")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FOTO", "Foto"),
                            ("DOCUMENTO", "Documento"),
                            ("FIRMA", "Firma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="ordenes.ordentrabajo",
                    ),
                ),
            ],
        ),
    ]
