# Generated by Django 4.2.24 on 2025-09-29 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipos", "0001_initial"),
        ("ordenes", "0004_historialot_evidencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalisisRCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criticidad",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MEDIA", "Media"),
                            ("BAJA", "Baja"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rpn",
                    models.IntegerField(help_text="Risk Priority Number calculado"),
                ),
                ("fecha_analisis", models.DateField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analisis_rcm",
                        to="equipos.equipo",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMEA_Detalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("funcion", models.TextField()),
                ("modo_falla", models.TextField()),
                ("causa", models.TextField()),
                ("efecto", models.TextField()),
                ("severidad", models.IntegerField(help_text="1-10")),
                ("ocurrencia", models.IntegerField(help_text="1-10")),
                ("deteccion", models.IntegerField(help_text="1-10")),
                ("rpn", models.IntegerField(help_text="S*O*D")),
                (
                    "rcm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fmea_detalles",
                        to="ordenes.analisisrcm",
                    ),
                ),
            ],
        ),
    ]
