# Generated by Django 4.2.24 on 2025-09-29 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="personal_fotos/"
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(
                        choices=[
                            ("MECANICO", "Mecánico"),
                            ("ELECTRICO", "Eléctrico"),
                            ("INSTRUMENTACION", "Instrumentación"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nivel", models.IntegerField(help_text="Nivel 1 o 2")),
                ("documento", models.CharField(max_length=50, unique=True)),
                ("contacto", models.CharField(max_length=100)),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        help_text="Solo para personal que tiene cuenta de usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
