# Generated by Django 4.2.24 on 2025-09-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_personal"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "horas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Horas trabajadas en el día",
                        max_digits=5,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción de la actividad realizada"
                    ),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_horas",
                        to="usuarios.personal",
                    ),
                ),
            ],
        ),
    ]
